CRITICAL - 2023-03-01 19:29:11 --> Undefined variable $users
in APPPATH\Views\users.php on line 21.
 1 APPPATH\Views\users.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $users', 'APPPATH\\Views\\users.php', 21)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('users', [], true)
 5 APPPATH\Controllers\UserCrud.php(17): view('users')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:29:46 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:30:06 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:30:08 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:32:11 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:32:32 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:32:38 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:32:38 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\User->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:41:30 --> Undefined variable $users
in APPPATH\Views\users-list.php on line 28.
 1 APPPATH\Views\users-list.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $users', 'APPPATH\\Views\\users-list.php', 28)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\users-list.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('users-list', [], true)
 5 APPPATH\Controllers\UserList.php(17): view('users-list')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserList->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserList))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 19:41:46 --> syntax error, unexpected token ";"
in APPPATH\Views\users-list.php on line 30.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('users-list', [], true)
 3 APPPATH\Controllers\UserList.php(17): view('users-list')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserList->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserList))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 20:10:58 --> foreach() argument must be of type array|object, null given
in APPPATH\Views\users-list.php on line 29.
 1 APPPATH\Views\users-list.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, null given', 'APPPATH\\Views\\users-list.php', 29)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\users-list.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('users-list', [], true)
 5 APPPATH\Controllers\UserList.php(20): view('users-list', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserList->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserList))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-01 20:32:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'cfpartners'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('cfpartners.mysq...', 'cfpartners', Object(SensitiveParameterValue), 'cfpartners', 3306, '', 0)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-01 20:32:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'191.177.187.198' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` ASC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-01 20:33:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'cfpartners'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('cfpartners.mysq...', 'cfpartners', Object(SensitiveParameterValue), 'cfpartners', 3306, '', 0)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-01 20:33:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'191.177.187.198' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` ASC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-01 20:41:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'cfpartners'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('cfpartners.mysq...', 'cfpartners', Object(SensitiveParameterValue), 'cfpartners', 3306, '', 0)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-01 20:41:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'191.177.187.198' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` ASC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-01 20:41:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'cfpartners'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('cfpartners.mysq...', 'cfpartners', Object(SensitiveParameterValue), 'cfpartners', 3306, '', 0)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'191.177.187.198' (using password: YES) in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-01 20:41:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'191.177.187.198' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` ASC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-01 20:44:11 --> Error connecting to the database: mysqli_sql_exception: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('186.202.28.227', 'cfpartners', Object(SensitiveParameterValue), 'cfpartners', 3306, '', 0)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu in C:\xampp\htdocs\cf-partners\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cf-partners\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cf-partners\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cf-partners\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cf-partners\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\cf-partners\app\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(934): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\cf-partners\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cf-partners\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cf-partners\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-01 20:44:11 --> Unable to connect to the database.
Main connection [MySQLi]: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` ASC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 21:09:56 --> Invalid file: "add_user.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('add_user.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('add_user', [], true)
 3 APPPATH\Controllers\UserCrud.php(19): view('add_user')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->create()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 21:11:40 --> Invalid file: "add_user.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('add_user.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('add_user', [], true)
 3 APPPATH\Controllers\UserCrud.php(19): view('add_user')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserCrud->create()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 23:21:09 --> Invalid file: "home.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('home', [], true)
 3 APPPATH\Controllers\Home.php(11): view('home')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 23:24:56 --> Invalid file: "home.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('home', [], true)
 3 APPPATH\Controllers\Home.php(11): view('home')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 23:25:16 --> Invalid file: "home.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('home', [], true)
 3 APPPATH\Controllers\Home.php(11): view('home')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-01 23:43:11 --> Call to undefined function link_tag()
in APPPATH\Views\templates\header.php on line 9.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('templates/header', [], true)
 4 APPPATH\Controllers\Home.php(10): view('templates/header')
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
